"""Command-line interface for regime_ot."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="regime-ot",
        description="Wasserstein market regime clustering experiments.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    download = subparsers.add_parser("download", help="Download adjusted close prices")
    download.add_argument("--tickers", nargs="+", required=True)
    download.add_argument("--start", required=True)
    download.add_argument("--end", default=None)
    download.add_argument("--output", default="data/raw/prices.csv")
    download.set_defaults(func=_download_command)

    run = subparsers.add_parser("run-wkmeans", help="Run Wasserstein k-means")
    run.add_argument("--ticker", required=True)
    run.add_argument("--start", default="2000-01-01")
    run.add_argument("--end", default=None)
    run.add_argument("--window", type=int, default=63)
    run.add_argument("--step", type=int, default=5)
    run.add_argument("--clusters", type=int, default=3)
    run.add_argument("--p", type=float, default=2.0)
    run.add_argument("--n-init", type=int, default=10)
    run.add_argument("--max-iter", type=int, default=100)
    run.add_argument("--cache", default=None)
    run.add_argument("--figures-dir", default="reports/figures")
    run.set_defaults(func=_run_wkmeans_command)

    report = subparsers.add_parser("make-report", help="Create a lightweight report stub")
    report.add_argument("--output", default="reports/summary.md")
    report.set_defaults(func=_make_report_command)
    return parser


def _download_command(args: argparse.Namespace) -> None:
    from regime_ot.data import download_prices, save_prices

    prices = download_prices(args.tickers, start=args.start, end=args.end)
    save_prices(prices, args.output)
    print(f"Saved {len(prices)} rows to {args.output}")


def _load_or_download_prices(args: argparse.Namespace) -> pd.DataFrame:
    from regime_ot.data import download_prices, load_cached_prices, save_prices

    cache = Path(args.cache) if args.cache else Path(f"data/raw/{args.ticker}.csv")
    if cache.exists():
        return load_cached_prices(cache)
    prices = download_prices([args.ticker], start=args.start, end=args.end)
    save_prices(prices, cache)
    return prices


def _run_wkmeans_command(args: argparse.Namespace) -> None:
    from regime_ot.baselines import extract_moment_features, run_standard_kmeans
    from regime_ot.evaluation import silhouette_from_distance_matrix
    from regime_ot.plotting import plot_centroid_distributions, plot_price_with_regimes
    from regime_ot.returns import clean_returns, compute_log_returns
    from regime_ot.wasserstein import pairwise_wasserstein_distance
    from regime_ot.windows import make_rolling_windows
    from regime_ot.wkmeans import WassersteinKMeans

    prices = _load_or_download_prices(args)
    price_series = prices[args.ticker] if args.ticker in prices else prices.iloc[:, 0]
    returns = clean_returns(compute_log_returns(price_series)).dropna()
    windows, dates = make_rolling_windows(returns, window_size=args.window, step=args.step)

    model = WassersteinKMeans(
        n_clusters=args.clusters,
        p=args.p,
        n_init=args.n_init,
        max_iter=args.max_iter,
        random_state=42,
    ).fit(windows)
    distance_matrix = pairwise_wasserstein_distance(windows, p=args.p)
    silhouette = silhouette_from_distance_matrix(distance_matrix, model.labels_)

    figures_dir = Path(args.figures_dir)
    figures_dir.mkdir(parents=True, exist_ok=True)
    price_fig, _ = plot_price_with_regimes(price_series, model.labels_, dates)
    price_fig.savefig(figures_dir / f"{args.ticker}_regimes.png", dpi=150)
    centroid_fig, _ = plot_centroid_distributions(model.centroids_)
    centroid_fig.savefig(figures_dir / f"{args.ticker}_centroids.png", dpi=150)

    features = extract_moment_features(windows)
    baseline = run_standard_kmeans(features, n_clusters=args.clusters)

    print(f"ticker={args.ticker}")
    print(f"windows={len(windows)} window_size={args.window} clusters={args.clusters}")
    print(f"wasserstein_inertia={model.inertia_:.8f}")
    print(f"wasserstein_silhouette={silhouette:.4f}")
    print(f"baseline_labels={sorted(set(baseline['labels']))}")
    print(f"figures_dir={figures_dir}")


def _make_report_command(args: argparse.Namespace) -> None:
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "# Wasserstein Market Regime Clustering Summary\n\n"
        "This report is generated by `python -m regime_ot.cli make-report`.\n"
        "Run the SPY experiment to populate figures and metrics.\n",
        encoding="utf-8",
    )
    print(f"Wrote {output}")


def main(argv: list[str] | None = None) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
